export const FETCH_COINS_SUCCESS = 'FETCH_COINS_SUCCESS';
export const FETCH_COIN_DETAILS_SUCCESS = 'FETCH_COIN_DETAILS_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';
export const DELETE_COIN_DETAILS = 'DELETE_COIN_DETAILS';
export const FETCH_MARKET_CAP = 'FETCH_MARKET_CAP';
